name: .Net Standard

on: 
  pull_request:
    paths:
      - 'src/*'
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .Net Standard
        uses: actions/setup-dotnet@master
      - name: build
        run: | 
          dotnet msbuild src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj -t:restore
          dotnet msbuild src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj -p:Configuration=Release
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and run .net core tests
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '3.1.414'
      - name: Test Mids
        run: |
          dotnet build src/MIDTesters.Core/MIDTesters.Core.csproj
          dotnet test src/MIDTesters.Core/MIDTesters.Core.csproj